# Generated by Django 4.1.3 on 2022-12-11 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(default="Hello, Cosmos! I haven't written a bio yet...", max_length=250)),
                ('pro_pic', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default-pro-pic.png', force_format='PNG', keep_meta=False, null=True, quality=100, scale=None, size=[256, 256], upload_to='')),
                ('banner_pic', models.ImageField(default='default-banner-pic.png', null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
