# Generated by Django 4.1.3 on 2022-12-11 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmos', '0003_post_post_images_post_reply_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
